welcome-message: 'Welcome to the server! :)'
required-players: 2
maximum-players: 8
countdown-seconds: 30
enable-rpg-compatibility: false
lobby-spawn:
  world: 'world'
  x: 0.5
  y: 64.0
  z: 0.5
  yaw: -180
  pitch: 0
arenas:
  # AVAILABLE GAME OPTIONS:
  #- BLOCK
  #- PVP
  #- SHOVELSPLEEF
  #- KNOCKOUT
  0:
    reset: true
    game: 'BLOCK'
    world: 'Map0'
    x: 100.5
    y: 64.0
    z: 100.5
    yaw: 0
    pitch: 0
    respawn:
      x: 0
      y: 64
      z: 20
      yaw: 180
      pitch: 0
  1:
    reset: false
    game: 'PVP'
    world: 'Map1'
    x: -100.5
    y: 64.0
    z: -100.5
    yaw: 0
    pitch: 0
    respawn:
      x: 0
      y: 64
      z: 20
      yaw: 180
      pitch: 0
