name: Minigame
version: '${project.version}'
main: com.xpkitty.minigame.Minigame
api-version: 1.18
authors: [ XpKitty ]
description: a minigame plugin
depend: [Multiverse-Core]
commands:
  arena:
    description: Used to join and leave arenas, open arena shop, kit and team menus
  lobby:
    description: Teleport to lobby
  shop:
    description: Admins only
    permission: minigame.admin
permissions:
  minigame.admin:
    default: op